import { executePaperTracker } from './executor.ts'

import type { SkillDefinition } from '../../../engine/contracts.ts'

export const paperTrackerSkill: SkillDefinition = {
  manifest: {
    id: 'paper-tracker',
    title: '论文追踪',
    summary:
      '围绕当前主题与分支，先让 LLM 生成发现意图，再走外部搜索、LLM 准入、阶段判断与终选，最后回写下一阶段结果。',
    description:
      '只保留起源论文作为真源后，paper-tracker 负责发现下一阶段候选、判断阶段窗口、决定是否分叉或合流，并把结构化研究决策写回 canonical。',
    recommendedAgentTarget: 'codex',
    defaultMode: 'agent-prompt',
    inputSchema: [
      { key: 'topicId', type: 'string', required: true, description: '要推进的主题 id。' },
      { key: 'branchId', type: 'string', required: false, description: '可选，指定要推进的分支。' },
      { key: 'stageIndex', type: 'number', required: false, description: '可选，指定要构建或校准的 stage。' },
      { key: 'problemNodeId', type: 'string', required: false, description: '可选，只聚焦某个问题节点。' },
      { key: 'stageMode', type: 'string', required: false, description: '默认 next-stage，每次只推进一个下一阶段。' },
      { key: 'discoverySource', type: 'string', required: false, description: '当前固定 external-only。' },
      { key: 'recalibrate', type: 'boolean', required: false, description: '是否对同一 branch/stage 复跑校准。' },
      { key: 'providerId', type: 'string', required: false, description: '直连模型 provider，可选 openai-compatible 或 anthropic。' },
      { key: 'model', type: 'string', required: false, description: '可选，显式指定模型。' },
      { key: 'temperature', type: 'number', required: false, description: '可选，生成温度。' },
      { key: 'maxTokens', type: 'number', required: false, description: '可选，最大输出 token。' },
      {
        key: 'windowPolicy',
        type: 'string',
        required: false,
        description: '窗口策略，可选 hybrid-auto-5m、auto 或 fixed。',
      },
      { key: 'allowMerge', type: 'boolean', required: false, description: '是否允许分支合流判断。' },
      { key: 'windowMonths', type: 'number', required: false, description: '可选，覆盖自动时间窗。' },
      { key: 'maxCandidates', type: 'number', required: false, description: '最终 shortlist 的最大候选数。', example: 6 },
      { key: 'mode', type: 'string', required: false, description: '业务模式，可选 dry-run、inspect、commit。' },
      { key: 'attachments', type: 'attachment[]', required: false, description: '可选，多模态附件。' },
    ],
    outputSchema: {
      discoveryPlan: 'object',
      discoverySummary: 'object',
      admittedCandidates: [
        {
          paperId: 'string',
          title: 'string',
          published: 'string',
          authors: 'string[]',
          candidateType: '"direct" | "branch" | "transfer"',
          confidence: 'number',
          status: 'string',
          why: 'string',
          citeIntent: '"supporting" | "contrasting" | "method-using" | "background" | undefined',
          branchAction: '"stay" | "split" | "merge" | "watch" | "no-candidate" | undefined',
          earliestWindowMonths: 'number | undefined',
          branchId: 'string | undefined',
          stageIndex: 'number | undefined',
          mergeTargetBranchIds: 'string[] | undefined',
          memorySignal: 'string | undefined',
          historyHits: 'number | undefined',
          queryHits: 'string[] | undefined',
          discoveryChannels: 'string[] | undefined',
        },
      ],
      candidates: [
        {
          paperId: 'string',
          title: 'string',
          published: 'string',
          authors: 'string[]',
          candidateType: '"direct" | "branch" | "transfer"',
          confidence: 'number',
          status: 'string',
          why: 'string',
          citeIntent: '"supporting" | "contrasting" | "method-using" | "background" | undefined',
          branchAction: '"stay" | "split" | "merge" | "watch" | "no-candidate" | undefined',
          earliestWindowMonths: 'number | undefined',
          branchId: 'string | undefined',
          stageIndex: 'number | undefined',
          mergeTargetBranchIds: 'string[] | undefined',
          memorySignal: 'string | undefined',
          historyHits: 'number | undefined',
          queryHits: 'string[] | undefined',
          discoveryChannels: 'string[] | undefined',
        },
      ],
      recommendations: 'Array<{paperId: string; candidateType: string; confidence: number; why: string; status: string}>',
      selectedCandidate: 'PaperTrackerCandidate | null',
      decisionSummary: 'string',
      branchDecisionRationale: 'string',
      branchAction: 'string',
      selectedBranch: 'object | null',
      stageWindow: 'object',
      stageWindowDecision: 'object',
      topicMemoryPatch: 'object',
      paperCatalogPatch: 'object',
      paperMetricsPatch: 'object',
      timelineContextPatch: 'object',
      runSummary: 'object',
    },
    artifacts: [
      {
        id: 'topic-memory',
        label: '主题运行记忆',
        relativePath: 'workflow/topic-memory.json',
        kind: 'json',
        retention: 'canonical',
      },
      {
        id: 'decision-memory',
        label: '决策记忆',
        relativePath: 'workflow/decision-memory.json',
        kind: 'json',
        retention: 'canonical',
      },
      {
        id: 'paper-catalog',
        label: '论文目录',
        relativePath: 'paper-catalog.json',
        kind: 'json',
        retention: 'canonical',
      },
      {
        id: 'paper-metrics',
        label: '论文指标',
        relativePath: 'paper-metrics.json',
        kind: 'json',
        retention: 'canonical',
      },
      {
        id: 'execution-memory',
        label: '执行记忆',
        relativePath: 'workflow/execution-memory.json',
        kind: 'json',
        retention: 'canonical',
      },
    ],
    localCommand: ['npx', 'ts-node', 'skills-backend/cli.ts', 'skill:run', 'paper-tracker'],
  },
  execute: executePaperTracker,
}
