export const TOPIC_WORKBENCH_DESKTOP_BREAKPOINT = 1024
export const TOPIC_WORKBENCH_DESKTOP_WIDTH = 392
export const TOPIC_WORKBENCH_DESKTOP_GAP = 24
export const TOPIC_WORKBENCH_DESKTOP_RESERVED_SPACE =
  TOPIC_WORKBENCH_DESKTOP_WIDTH + TOPIC_WORKBENCH_DESKTOP_GAP

export function isTopicWorkbenchDesktopViewport(width: number) {
  return width >= TOPIC_WORKBENCH_DESKTOP_BREAKPOINT
}
